/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InspirationsRouteImport } from './routes/inspirations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InspirationAssetsAssetRouteImport } from './routes/inspiration-assets/asset'
import { Route as AlbumsFolderRouteImport } from './routes/albums/$folder'
import { Route as ApiSunoSettingsRouteImport } from './routes/api/suno/settings'
import { Route as ApiSunoMediaRouteImport } from './routes/api/suno/media'
import { Route as ApiSunoInspirationsRouteImport } from './routes/api/suno/inspirations'
import { Route as ApiSunoImportRouteImport } from './routes/api/suno/import'
import { Route as ApiSunoDownloadRouteImport } from './routes/api/suno/download'
import { Route as ApiSunoAlbumsRouteImport } from './routes/api/suno/albums'
import { Route as ApiSunoTracksDeleteRouteImport } from './routes/api/suno/tracks/delete'
import { Route as ApiSunoInspirationsUploadRouteImport } from './routes/api/suno/inspirations/upload'
import { Route as ApiSunoInspirationsSettingsRouteImport } from './routes/api/suno/inspirations/settings'
import { Route as ApiSunoInspirationsMediaRouteImport } from './routes/api/suno/inspirations/media'
import { Route as ApiSunoInspirationsDeleteRouteImport } from './routes/api/suno/inspirations/delete'
import { Route as ApiSunoInspirationsAssetRouteImport } from './routes/api/suno/inspirations/asset'
import { Route as ApiSunoAlbumsFolderVideoRouteImport } from './routes/api/suno/albums/$folder/video'
import { Route as ApiSunoAlbumsFolderUploadRouteImport } from './routes/api/suno/albums/$folder/upload'
import { Route as ApiSunoAlbumsFolderSuggestionsRouteImport } from './routes/api/suno/albums/$folder/suggestions'
import { Route as ApiSunoAlbumsFolderPublishRouteImport } from './routes/api/suno/albums/$folder/publish'
import { Route as ApiSunoAlbumsFolderGenerationRouteImport } from './routes/api/suno/albums/$folder/generation'
import { Route as ApiSunoAlbumsFolderDeleteRouteImport } from './routes/api/suno/albums/$folder/delete'
import { Route as ApiSunoAlbumsFolderCoverRouteImport } from './routes/api/suno/albums/$folder/cover'
import { Route as ApiSunoInspirationsAssetsIdFileRouteImport } from './routes/api/suno/inspirations/assets/$id/$file'

const InspirationsRoute = InspirationsRouteImport.update({
  id: '/inspirations',
  path: '/inspirations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationAssetsAssetRoute = InspirationAssetsAssetRouteImport.update({
  id: '/inspiration-assets/asset',
  path: '/inspiration-assets/asset',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsFolderRoute = AlbumsFolderRouteImport.update({
  id: '/albums/$folder',
  path: '/albums/$folder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSunoSettingsRoute = ApiSunoSettingsRouteImport.update({
  id: '/api/suno/settings',
  path: '/api/suno/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSunoMediaRoute = ApiSunoMediaRouteImport.update({
  id: '/api/suno/media',
  path: '/api/suno/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSunoInspirationsRoute = ApiSunoInspirationsRouteImport.update({
  id: '/api/suno/inspirations',
  path: '/api/suno/inspirations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSunoImportRoute = ApiSunoImportRouteImport.update({
  id: '/api/suno/import',
  path: '/api/suno/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSunoDownloadRoute = ApiSunoDownloadRouteImport.update({
  id: '/api/suno/download',
  path: '/api/suno/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSunoAlbumsRoute = ApiSunoAlbumsRouteImport.update({
  id: '/api/suno/albums',
  path: '/api/suno/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSunoTracksDeleteRoute = ApiSunoTracksDeleteRouteImport.update({
  id: '/api/suno/tracks/delete',
  path: '/api/suno/tracks/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSunoInspirationsUploadRoute =
  ApiSunoInspirationsUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => ApiSunoInspirationsRoute,
  } as any)
const ApiSunoInspirationsSettingsRoute =
  ApiSunoInspirationsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ApiSunoInspirationsRoute,
  } as any)
const ApiSunoInspirationsMediaRoute =
  ApiSunoInspirationsMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => ApiSunoInspirationsRoute,
  } as any)
const ApiSunoInspirationsDeleteRoute =
  ApiSunoInspirationsDeleteRouteImport.update({
    id: '/delete',
    path: '/delete',
    getParentRoute: () => ApiSunoInspirationsRoute,
  } as any)
const ApiSunoInspirationsAssetRoute =
  ApiSunoInspirationsAssetRouteImport.update({
    id: '/asset',
    path: '/asset',
    getParentRoute: () => ApiSunoInspirationsRoute,
  } as any)
const ApiSunoAlbumsFolderVideoRoute =
  ApiSunoAlbumsFolderVideoRouteImport.update({
    id: '/$folder/video',
    path: '/$folder/video',
    getParentRoute: () => ApiSunoAlbumsRoute,
  } as any)
const ApiSunoAlbumsFolderUploadRoute =
  ApiSunoAlbumsFolderUploadRouteImport.update({
    id: '/$folder/upload',
    path: '/$folder/upload',
    getParentRoute: () => ApiSunoAlbumsRoute,
  } as any)
const ApiSunoAlbumsFolderSuggestionsRoute =
  ApiSunoAlbumsFolderSuggestionsRouteImport.update({
    id: '/$folder/suggestions',
    path: '/$folder/suggestions',
    getParentRoute: () => ApiSunoAlbumsRoute,
  } as any)
const ApiSunoAlbumsFolderPublishRoute =
  ApiSunoAlbumsFolderPublishRouteImport.update({
    id: '/$folder/publish',
    path: '/$folder/publish',
    getParentRoute: () => ApiSunoAlbumsRoute,
  } as any)
const ApiSunoAlbumsFolderGenerationRoute =
  ApiSunoAlbumsFolderGenerationRouteImport.update({
    id: '/$folder/generation',
    path: '/$folder/generation',
    getParentRoute: () => ApiSunoAlbumsRoute,
  } as any)
const ApiSunoAlbumsFolderDeleteRoute =
  ApiSunoAlbumsFolderDeleteRouteImport.update({
    id: '/$folder/delete',
    path: '/$folder/delete',
    getParentRoute: () => ApiSunoAlbumsRoute,
  } as any)
const ApiSunoAlbumsFolderCoverRoute =
  ApiSunoAlbumsFolderCoverRouteImport.update({
    id: '/$folder/cover',
    path: '/$folder/cover',
    getParentRoute: () => ApiSunoAlbumsRoute,
  } as any)
const ApiSunoInspirationsAssetsIdFileRoute =
  ApiSunoInspirationsAssetsIdFileRouteImport.update({
    id: '/assets/$id/$file',
    path: '/assets/$id/$file',
    getParentRoute: () => ApiSunoInspirationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inspirations': typeof InspirationsRoute
  '/albums/$folder': typeof AlbumsFolderRoute
  '/inspiration-assets/asset': typeof InspirationAssetsAssetRoute
  '/api/suno/albums': typeof ApiSunoAlbumsRouteWithChildren
  '/api/suno/download': typeof ApiSunoDownloadRoute
  '/api/suno/import': typeof ApiSunoImportRoute
  '/api/suno/inspirations': typeof ApiSunoInspirationsRouteWithChildren
  '/api/suno/media': typeof ApiSunoMediaRoute
  '/api/suno/settings': typeof ApiSunoSettingsRoute
  '/api/suno/inspirations/asset': typeof ApiSunoInspirationsAssetRoute
  '/api/suno/inspirations/delete': typeof ApiSunoInspirationsDeleteRoute
  '/api/suno/inspirations/media': typeof ApiSunoInspirationsMediaRoute
  '/api/suno/inspirations/settings': typeof ApiSunoInspirationsSettingsRoute
  '/api/suno/inspirations/upload': typeof ApiSunoInspirationsUploadRoute
  '/api/suno/tracks/delete': typeof ApiSunoTracksDeleteRoute
  '/api/suno/albums/$folder/cover': typeof ApiSunoAlbumsFolderCoverRoute
  '/api/suno/albums/$folder/delete': typeof ApiSunoAlbumsFolderDeleteRoute
  '/api/suno/albums/$folder/generation': typeof ApiSunoAlbumsFolderGenerationRoute
  '/api/suno/albums/$folder/publish': typeof ApiSunoAlbumsFolderPublishRoute
  '/api/suno/albums/$folder/suggestions': typeof ApiSunoAlbumsFolderSuggestionsRoute
  '/api/suno/albums/$folder/upload': typeof ApiSunoAlbumsFolderUploadRoute
  '/api/suno/albums/$folder/video': typeof ApiSunoAlbumsFolderVideoRoute
  '/api/suno/inspirations/assets/$id/$file': typeof ApiSunoInspirationsAssetsIdFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inspirations': typeof InspirationsRoute
  '/albums/$folder': typeof AlbumsFolderRoute
  '/inspiration-assets/asset': typeof InspirationAssetsAssetRoute
  '/api/suno/albums': typeof ApiSunoAlbumsRouteWithChildren
  '/api/suno/download': typeof ApiSunoDownloadRoute
  '/api/suno/import': typeof ApiSunoImportRoute
  '/api/suno/inspirations': typeof ApiSunoInspirationsRouteWithChildren
  '/api/suno/media': typeof ApiSunoMediaRoute
  '/api/suno/settings': typeof ApiSunoSettingsRoute
  '/api/suno/inspirations/asset': typeof ApiSunoInspirationsAssetRoute
  '/api/suno/inspirations/delete': typeof ApiSunoInspirationsDeleteRoute
  '/api/suno/inspirations/media': typeof ApiSunoInspirationsMediaRoute
  '/api/suno/inspirations/settings': typeof ApiSunoInspirationsSettingsRoute
  '/api/suno/inspirations/upload': typeof ApiSunoInspirationsUploadRoute
  '/api/suno/tracks/delete': typeof ApiSunoTracksDeleteRoute
  '/api/suno/albums/$folder/cover': typeof ApiSunoAlbumsFolderCoverRoute
  '/api/suno/albums/$folder/delete': typeof ApiSunoAlbumsFolderDeleteRoute
  '/api/suno/albums/$folder/generation': typeof ApiSunoAlbumsFolderGenerationRoute
  '/api/suno/albums/$folder/publish': typeof ApiSunoAlbumsFolderPublishRoute
  '/api/suno/albums/$folder/suggestions': typeof ApiSunoAlbumsFolderSuggestionsRoute
  '/api/suno/albums/$folder/upload': typeof ApiSunoAlbumsFolderUploadRoute
  '/api/suno/albums/$folder/video': typeof ApiSunoAlbumsFolderVideoRoute
  '/api/suno/inspirations/assets/$id/$file': typeof ApiSunoInspirationsAssetsIdFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inspirations': typeof InspirationsRoute
  '/albums/$folder': typeof AlbumsFolderRoute
  '/inspiration-assets/asset': typeof InspirationAssetsAssetRoute
  '/api/suno/albums': typeof ApiSunoAlbumsRouteWithChildren
  '/api/suno/download': typeof ApiSunoDownloadRoute
  '/api/suno/import': typeof ApiSunoImportRoute
  '/api/suno/inspirations': typeof ApiSunoInspirationsRouteWithChildren
  '/api/suno/media': typeof ApiSunoMediaRoute
  '/api/suno/settings': typeof ApiSunoSettingsRoute
  '/api/suno/inspirations/asset': typeof ApiSunoInspirationsAssetRoute
  '/api/suno/inspirations/delete': typeof ApiSunoInspirationsDeleteRoute
  '/api/suno/inspirations/media': typeof ApiSunoInspirationsMediaRoute
  '/api/suno/inspirations/settings': typeof ApiSunoInspirationsSettingsRoute
  '/api/suno/inspirations/upload': typeof ApiSunoInspirationsUploadRoute
  '/api/suno/tracks/delete': typeof ApiSunoTracksDeleteRoute
  '/api/suno/albums/$folder/cover': typeof ApiSunoAlbumsFolderCoverRoute
  '/api/suno/albums/$folder/delete': typeof ApiSunoAlbumsFolderDeleteRoute
  '/api/suno/albums/$folder/generation': typeof ApiSunoAlbumsFolderGenerationRoute
  '/api/suno/albums/$folder/publish': typeof ApiSunoAlbumsFolderPublishRoute
  '/api/suno/albums/$folder/suggestions': typeof ApiSunoAlbumsFolderSuggestionsRoute
  '/api/suno/albums/$folder/upload': typeof ApiSunoAlbumsFolderUploadRoute
  '/api/suno/albums/$folder/video': typeof ApiSunoAlbumsFolderVideoRoute
  '/api/suno/inspirations/assets/$id/$file': typeof ApiSunoInspirationsAssetsIdFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inspirations'
    | '/albums/$folder'
    | '/inspiration-assets/asset'
    | '/api/suno/albums'
    | '/api/suno/download'
    | '/api/suno/import'
    | '/api/suno/inspirations'
    | '/api/suno/media'
    | '/api/suno/settings'
    | '/api/suno/inspirations/asset'
    | '/api/suno/inspirations/delete'
    | '/api/suno/inspirations/media'
    | '/api/suno/inspirations/settings'
    | '/api/suno/inspirations/upload'
    | '/api/suno/tracks/delete'
    | '/api/suno/albums/$folder/cover'
    | '/api/suno/albums/$folder/delete'
    | '/api/suno/albums/$folder/generation'
    | '/api/suno/albums/$folder/publish'
    | '/api/suno/albums/$folder/suggestions'
    | '/api/suno/albums/$folder/upload'
    | '/api/suno/albums/$folder/video'
    | '/api/suno/inspirations/assets/$id/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inspirations'
    | '/albums/$folder'
    | '/inspiration-assets/asset'
    | '/api/suno/albums'
    | '/api/suno/download'
    | '/api/suno/import'
    | '/api/suno/inspirations'
    | '/api/suno/media'
    | '/api/suno/settings'
    | '/api/suno/inspirations/asset'
    | '/api/suno/inspirations/delete'
    | '/api/suno/inspirations/media'
    | '/api/suno/inspirations/settings'
    | '/api/suno/inspirations/upload'
    | '/api/suno/tracks/delete'
    | '/api/suno/albums/$folder/cover'
    | '/api/suno/albums/$folder/delete'
    | '/api/suno/albums/$folder/generation'
    | '/api/suno/albums/$folder/publish'
    | '/api/suno/albums/$folder/suggestions'
    | '/api/suno/albums/$folder/upload'
    | '/api/suno/albums/$folder/video'
    | '/api/suno/inspirations/assets/$id/$file'
  id:
    | '__root__'
    | '/'
    | '/inspirations'
    | '/albums/$folder'
    | '/inspiration-assets/asset'
    | '/api/suno/albums'
    | '/api/suno/download'
    | '/api/suno/import'
    | '/api/suno/inspirations'
    | '/api/suno/media'
    | '/api/suno/settings'
    | '/api/suno/inspirations/asset'
    | '/api/suno/inspirations/delete'
    | '/api/suno/inspirations/media'
    | '/api/suno/inspirations/settings'
    | '/api/suno/inspirations/upload'
    | '/api/suno/tracks/delete'
    | '/api/suno/albums/$folder/cover'
    | '/api/suno/albums/$folder/delete'
    | '/api/suno/albums/$folder/generation'
    | '/api/suno/albums/$folder/publish'
    | '/api/suno/albums/$folder/suggestions'
    | '/api/suno/albums/$folder/upload'
    | '/api/suno/albums/$folder/video'
    | '/api/suno/inspirations/assets/$id/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InspirationsRoute: typeof InspirationsRoute
  AlbumsFolderRoute: typeof AlbumsFolderRoute
  InspirationAssetsAssetRoute: typeof InspirationAssetsAssetRoute
  ApiSunoAlbumsRoute: typeof ApiSunoAlbumsRouteWithChildren
  ApiSunoDownloadRoute: typeof ApiSunoDownloadRoute
  ApiSunoImportRoute: typeof ApiSunoImportRoute
  ApiSunoInspirationsRoute: typeof ApiSunoInspirationsRouteWithChildren
  ApiSunoMediaRoute: typeof ApiSunoMediaRoute
  ApiSunoSettingsRoute: typeof ApiSunoSettingsRoute
  ApiSunoTracksDeleteRoute: typeof ApiSunoTracksDeleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inspirations': {
      id: '/inspirations'
      path: '/inspirations'
      fullPath: '/inspirations'
      preLoaderRoute: typeof InspirationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration-assets/asset': {
      id: '/inspiration-assets/asset'
      path: '/inspiration-assets/asset'
      fullPath: '/inspiration-assets/asset'
      preLoaderRoute: typeof InspirationAssetsAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$folder': {
      id: '/albums/$folder'
      path: '/albums/$folder'
      fullPath: '/albums/$folder'
      preLoaderRoute: typeof AlbumsFolderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suno/settings': {
      id: '/api/suno/settings'
      path: '/api/suno/settings'
      fullPath: '/api/suno/settings'
      preLoaderRoute: typeof ApiSunoSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suno/media': {
      id: '/api/suno/media'
      path: '/api/suno/media'
      fullPath: '/api/suno/media'
      preLoaderRoute: typeof ApiSunoMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suno/inspirations': {
      id: '/api/suno/inspirations'
      path: '/api/suno/inspirations'
      fullPath: '/api/suno/inspirations'
      preLoaderRoute: typeof ApiSunoInspirationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suno/import': {
      id: '/api/suno/import'
      path: '/api/suno/import'
      fullPath: '/api/suno/import'
      preLoaderRoute: typeof ApiSunoImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suno/download': {
      id: '/api/suno/download'
      path: '/api/suno/download'
      fullPath: '/api/suno/download'
      preLoaderRoute: typeof ApiSunoDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suno/albums': {
      id: '/api/suno/albums'
      path: '/api/suno/albums'
      fullPath: '/api/suno/albums'
      preLoaderRoute: typeof ApiSunoAlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suno/tracks/delete': {
      id: '/api/suno/tracks/delete'
      path: '/api/suno/tracks/delete'
      fullPath: '/api/suno/tracks/delete'
      preLoaderRoute: typeof ApiSunoTracksDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suno/inspirations/upload': {
      id: '/api/suno/inspirations/upload'
      path: '/upload'
      fullPath: '/api/suno/inspirations/upload'
      preLoaderRoute: typeof ApiSunoInspirationsUploadRouteImport
      parentRoute: typeof ApiSunoInspirationsRoute
    }
    '/api/suno/inspirations/settings': {
      id: '/api/suno/inspirations/settings'
      path: '/settings'
      fullPath: '/api/suno/inspirations/settings'
      preLoaderRoute: typeof ApiSunoInspirationsSettingsRouteImport
      parentRoute: typeof ApiSunoInspirationsRoute
    }
    '/api/suno/inspirations/media': {
      id: '/api/suno/inspirations/media'
      path: '/media'
      fullPath: '/api/suno/inspirations/media'
      preLoaderRoute: typeof ApiSunoInspirationsMediaRouteImport
      parentRoute: typeof ApiSunoInspirationsRoute
    }
    '/api/suno/inspirations/delete': {
      id: '/api/suno/inspirations/delete'
      path: '/delete'
      fullPath: '/api/suno/inspirations/delete'
      preLoaderRoute: typeof ApiSunoInspirationsDeleteRouteImport
      parentRoute: typeof ApiSunoInspirationsRoute
    }
    '/api/suno/inspirations/asset': {
      id: '/api/suno/inspirations/asset'
      path: '/asset'
      fullPath: '/api/suno/inspirations/asset'
      preLoaderRoute: typeof ApiSunoInspirationsAssetRouteImport
      parentRoute: typeof ApiSunoInspirationsRoute
    }
    '/api/suno/albums/$folder/video': {
      id: '/api/suno/albums/$folder/video'
      path: '/$folder/video'
      fullPath: '/api/suno/albums/$folder/video'
      preLoaderRoute: typeof ApiSunoAlbumsFolderVideoRouteImport
      parentRoute: typeof ApiSunoAlbumsRoute
    }
    '/api/suno/albums/$folder/upload': {
      id: '/api/suno/albums/$folder/upload'
      path: '/$folder/upload'
      fullPath: '/api/suno/albums/$folder/upload'
      preLoaderRoute: typeof ApiSunoAlbumsFolderUploadRouteImport
      parentRoute: typeof ApiSunoAlbumsRoute
    }
    '/api/suno/albums/$folder/suggestions': {
      id: '/api/suno/albums/$folder/suggestions'
      path: '/$folder/suggestions'
      fullPath: '/api/suno/albums/$folder/suggestions'
      preLoaderRoute: typeof ApiSunoAlbumsFolderSuggestionsRouteImport
      parentRoute: typeof ApiSunoAlbumsRoute
    }
    '/api/suno/albums/$folder/publish': {
      id: '/api/suno/albums/$folder/publish'
      path: '/$folder/publish'
      fullPath: '/api/suno/albums/$folder/publish'
      preLoaderRoute: typeof ApiSunoAlbumsFolderPublishRouteImport
      parentRoute: typeof ApiSunoAlbumsRoute
    }
    '/api/suno/albums/$folder/generation': {
      id: '/api/suno/albums/$folder/generation'
      path: '/$folder/generation'
      fullPath: '/api/suno/albums/$folder/generation'
      preLoaderRoute: typeof ApiSunoAlbumsFolderGenerationRouteImport
      parentRoute: typeof ApiSunoAlbumsRoute
    }
    '/api/suno/albums/$folder/delete': {
      id: '/api/suno/albums/$folder/delete'
      path: '/$folder/delete'
      fullPath: '/api/suno/albums/$folder/delete'
      preLoaderRoute: typeof ApiSunoAlbumsFolderDeleteRouteImport
      parentRoute: typeof ApiSunoAlbumsRoute
    }
    '/api/suno/albums/$folder/cover': {
      id: '/api/suno/albums/$folder/cover'
      path: '/$folder/cover'
      fullPath: '/api/suno/albums/$folder/cover'
      preLoaderRoute: typeof ApiSunoAlbumsFolderCoverRouteImport
      parentRoute: typeof ApiSunoAlbumsRoute
    }
    '/api/suno/inspirations/assets/$id/$file': {
      id: '/api/suno/inspirations/assets/$id/$file'
      path: '/assets/$id/$file'
      fullPath: '/api/suno/inspirations/assets/$id/$file'
      preLoaderRoute: typeof ApiSunoInspirationsAssetsIdFileRouteImport
      parentRoute: typeof ApiSunoInspirationsRoute
    }
  }
}

interface ApiSunoAlbumsRouteChildren {
  ApiSunoAlbumsFolderCoverRoute: typeof ApiSunoAlbumsFolderCoverRoute
  ApiSunoAlbumsFolderDeleteRoute: typeof ApiSunoAlbumsFolderDeleteRoute
  ApiSunoAlbumsFolderGenerationRoute: typeof ApiSunoAlbumsFolderGenerationRoute
  ApiSunoAlbumsFolderPublishRoute: typeof ApiSunoAlbumsFolderPublishRoute
  ApiSunoAlbumsFolderSuggestionsRoute: typeof ApiSunoAlbumsFolderSuggestionsRoute
  ApiSunoAlbumsFolderUploadRoute: typeof ApiSunoAlbumsFolderUploadRoute
  ApiSunoAlbumsFolderVideoRoute: typeof ApiSunoAlbumsFolderVideoRoute
}

const ApiSunoAlbumsRouteChildren: ApiSunoAlbumsRouteChildren = {
  ApiSunoAlbumsFolderCoverRoute: ApiSunoAlbumsFolderCoverRoute,
  ApiSunoAlbumsFolderDeleteRoute: ApiSunoAlbumsFolderDeleteRoute,
  ApiSunoAlbumsFolderGenerationRoute: ApiSunoAlbumsFolderGenerationRoute,
  ApiSunoAlbumsFolderPublishRoute: ApiSunoAlbumsFolderPublishRoute,
  ApiSunoAlbumsFolderSuggestionsRoute: ApiSunoAlbumsFolderSuggestionsRoute,
  ApiSunoAlbumsFolderUploadRoute: ApiSunoAlbumsFolderUploadRoute,
  ApiSunoAlbumsFolderVideoRoute: ApiSunoAlbumsFolderVideoRoute,
}

const ApiSunoAlbumsRouteWithChildren = ApiSunoAlbumsRoute._addFileChildren(
  ApiSunoAlbumsRouteChildren,
)

interface ApiSunoInspirationsRouteChildren {
  ApiSunoInspirationsAssetRoute: typeof ApiSunoInspirationsAssetRoute
  ApiSunoInspirationsDeleteRoute: typeof ApiSunoInspirationsDeleteRoute
  ApiSunoInspirationsMediaRoute: typeof ApiSunoInspirationsMediaRoute
  ApiSunoInspirationsSettingsRoute: typeof ApiSunoInspirationsSettingsRoute
  ApiSunoInspirationsUploadRoute: typeof ApiSunoInspirationsUploadRoute
  ApiSunoInspirationsAssetsIdFileRoute: typeof ApiSunoInspirationsAssetsIdFileRoute
}

const ApiSunoInspirationsRouteChildren: ApiSunoInspirationsRouteChildren = {
  ApiSunoInspirationsAssetRoute: ApiSunoInspirationsAssetRoute,
  ApiSunoInspirationsDeleteRoute: ApiSunoInspirationsDeleteRoute,
  ApiSunoInspirationsMediaRoute: ApiSunoInspirationsMediaRoute,
  ApiSunoInspirationsSettingsRoute: ApiSunoInspirationsSettingsRoute,
  ApiSunoInspirationsUploadRoute: ApiSunoInspirationsUploadRoute,
  ApiSunoInspirationsAssetsIdFileRoute: ApiSunoInspirationsAssetsIdFileRoute,
}

const ApiSunoInspirationsRouteWithChildren =
  ApiSunoInspirationsRoute._addFileChildren(ApiSunoInspirationsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InspirationsRoute: InspirationsRoute,
  AlbumsFolderRoute: AlbumsFolderRoute,
  InspirationAssetsAssetRoute: InspirationAssetsAssetRoute,
  ApiSunoAlbumsRoute: ApiSunoAlbumsRouteWithChildren,
  ApiSunoDownloadRoute: ApiSunoDownloadRoute,
  ApiSunoImportRoute: ApiSunoImportRoute,
  ApiSunoInspirationsRoute: ApiSunoInspirationsRouteWithChildren,
  ApiSunoMediaRoute: ApiSunoMediaRoute,
  ApiSunoSettingsRoute: ApiSunoSettingsRoute,
  ApiSunoTracksDeleteRoute: ApiSunoTracksDeleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
